### ISSUE TITLE
Review IAM Roles and Policies

### ISSUE THREAD

**Issue by briri** [CDLUC3/dmp-hub-cfn#1]
Review and scale back IAM Roles and Policies

In most cases we used FullAccess for IAM permissions. We should coordinate with IAS to determine how to review the permissions that have actually been used by each resource and scale back the CF templates (and SAM template).

**Comment by marisastrong** [comment]
Thanks Brian - I added this to the UC3 Operations & Infrastructure Board

https://github.com/orgs/CDLUC3/projects/8/views/1
________________________________
From: Brian Riley ***@***.***>
Sent: Wednesday, September 28, 2022 10:46 AM
To: CDLUC3/dmp-hub-cfn ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [CDLUC3/dmp-hub-cfn] Review IAM Roles and Policies (Issue #1)


CAUTION: EXTERNAL EMAIL

Review and scale back IAM Roles and Policies

**Comment by marisastrong** [comment]
Marisa needs to request increased permissions for visibility in AWS Console.
