### ISSUE TITLE
Add Cidr based ingress/egress rules for Dynamo

### ISSUE THREAD

**Issue by briri** [CDLUC3/dmp-hub-cfn#15]
Add ingress/egress rules for the DynamoDB for the UCOP CidrBlock so that as a developer, I can access the database and run queries through an editor.

See https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/security-group-rules-reference.html#sg-rules-db-server

Not sure if this would require a NAT to be added to the private subnets.

**Comment by briri** [comment]
Also need to do this for RDS

**Comment by ashleygould** [comment]
follow up with Brian

**Comment by briri** [comment]
Yes, this will still be useful, especially in the stg/prd environment at least early on. 

The ultimate goal would be for us to NOT need this in any environment. It would be best for me to manipulate Dynamo records via the DMPTool UI.

I'm not sure what's involved to set this up though and the degree of difficulty. I am able to edit records via the CLI for the time being (and directly through the console in dev) and I've only had to do so a few times so far.

**Comment by briri** [comment]
I got this working using AWS' NoSQL Workbench. I am able to connect to the both the dev and stg/prd accounts.

Will use this approach or the CLI if I need to manipulate records in the stg/prd env.
